labels: 
  0: "unlabeled"
  1: "crater"
  2: "crater_eject"
  3: "channel"
  4: "delta"
  5: "mesa"
  6: "polygons"
  7: "wrinkle_ridge"
  8: "lava_tube"
  9: "lava_flow"
  10: "tranverse_sand_ridges"
  11: "curve_dunes"
  12: "yardangs"
  13: "gullies"
  14: "dark_slope_streak"
  15: "mound"
  16: "ridge"
  17: "cliff"
  18: "smooth_terrain"
